version: 2
updates:
  - package-ecosystem: "npm"
    directory: "."
    target-branch: "main"
    schedule:
      interval: "weekly"
    ignore: 
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "gitsubmodule"
    directory: "/modules"
    schedule:
      interval: "daily"
    labels:
      - "submodules"

