remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: CryptOpt: Verified Compilation with Random Program Search for Cryptographic Primitives
description: An Automatic Optimizer for Cryptographic Primitives.
