name: Docker build

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build and test inside of the Docker image
    runs-on: ubuntu-22.04

    steps:

    - name: env
      run: 'echo ${ALLOW_DIFF}'
      env: 
        ALLOW_DIFF: 1

    - name: Build and push Docker images
      uses: docker/build-push-action@v4
      with:
        push: false

